version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/web:cached
    ports:
      - 3434:3000
    command: sh -c "npm run dev"
