import React from 'react';
import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head';
import Layout from "components/layouts";
import { Auth0Provider } from "@auth0/auth0-react";

export default function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Auth0Provider
          domain={process.env["NEXT_PUBLIC_AUTH0_DOMAIN"]!}
          clientId={process.env["NEXT_PUBLIC_AUTH0_CLIENT_ID"]!}
          authorizationParams={{
            redirect_uri: `${process.env["NEXT_PUBLIC_FRONT_URL"]}/mypage`,
            audience: process.env["NEXT_PUBLIC_AUTH0_AUDIENCE"],
          }}
        >
          <Component {...pageProps} />
        </Auth0Provider>
      </Layout>
    </>
  )
}
